apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: UjEyMzRy
  MYSQL_PASSWORD: Q2xhcnVzd2F5XzE=


  # myrootpassword: UjEyMzRy
  # mypassword: Q2xhcnVzd2F5XzE=

  # MYSQL_ROOT_PASSWORD: UjEyMzRy
  # MYSQL_PASSWORD: Q2xhcnVzd2F5XzE=   bunu kullanmak daha avantajlı karışıklık olmaz kolay, POSIX formatında yazıldığı için envfrom kullanabilirim 
# bir sürü env olduğunu düşünün valuefrom çok vakit alır tek tek env lere name key atamak. POSIX formatında yazıp envfrom ile tek bir name ile iş bitirmek daha mantıklı